CREATE TABLE IF NOT EXISTS CLIENTE (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sobrenome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    saldo DECIMAL (10,2) DEFAULT 0.00
);